// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: hello/hello.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcStatusCode int32

const (
	GrpcStatusCode_OK                  GrpcStatusCode = 0
	GrpcStatusCode_CANCELLED           GrpcStatusCode = 1
	GrpcStatusCode_UNKNOWN             GrpcStatusCode = 2
	GrpcStatusCode_INVALID_ARGUMENT    GrpcStatusCode = 3
	GrpcStatusCode_DEADLINE_EXCEEDED   GrpcStatusCode = 4
	GrpcStatusCode_NOT_FOUND           GrpcStatusCode = 5
	GrpcStatusCode_ALREADY_EXISTS      GrpcStatusCode = 6
	GrpcStatusCode_PERMISSION_DENIED   GrpcStatusCode = 7
	GrpcStatusCode_RESOURCE_EXHAUSTED  GrpcStatusCode = 8
	GrpcStatusCode_FAILED_PRECONDITION GrpcStatusCode = 9
	GrpcStatusCode_ABORTED             GrpcStatusCode = 10
	GrpcStatusCode_OUT_OF_RANGE        GrpcStatusCode = 11
	GrpcStatusCode_UNIMPLEMENTED       GrpcStatusCode = 12
	GrpcStatusCode_INTERNAL            GrpcStatusCode = 13
	GrpcStatusCode_UNAVAILABLE         GrpcStatusCode = 14
	GrpcStatusCode_DATA_LOSS           GrpcStatusCode = 15
	GrpcStatusCode_UNAUTHENTICATED     GrpcStatusCode = 16
)

// Enum value maps for GrpcStatusCode.
var (
	GrpcStatusCode_name = map[int32]string{
		0:  "OK",
		1:  "CANCELLED",
		2:  "UNKNOWN",
		3:  "INVALID_ARGUMENT",
		4:  "DEADLINE_EXCEEDED",
		5:  "NOT_FOUND",
		6:  "ALREADY_EXISTS",
		7:  "PERMISSION_DENIED",
		8:  "RESOURCE_EXHAUSTED",
		9:  "FAILED_PRECONDITION",
		10: "ABORTED",
		11: "OUT_OF_RANGE",
		12: "UNIMPLEMENTED",
		13: "INTERNAL",
		14: "UNAVAILABLE",
		15: "DATA_LOSS",
		16: "UNAUTHENTICATED",
	}
	GrpcStatusCode_value = map[string]int32{
		"OK":                  0,
		"CANCELLED":           1,
		"UNKNOWN":             2,
		"INVALID_ARGUMENT":    3,
		"DEADLINE_EXCEEDED":   4,
		"NOT_FOUND":           5,
		"ALREADY_EXISTS":      6,
		"PERMISSION_DENIED":   7,
		"RESOURCE_EXHAUSTED":  8,
		"FAILED_PRECONDITION": 9,
		"ABORTED":             10,
		"OUT_OF_RANGE":        11,
		"UNIMPLEMENTED":       12,
		"INTERNAL":            13,
		"UNAVAILABLE":         14,
		"DATA_LOSS":           15,
		"UNAUTHENTICATED":     16,
	}
)

func (x GrpcStatusCode) Enum() *GrpcStatusCode {
	p := new(GrpcStatusCode)
	*p = x
	return p
}

func (x GrpcStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrpcStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_hello_hello_proto_enumTypes[0].Descriptor()
}

func (GrpcStatusCode) Type() protoreflect.EnumType {
	return &file_hello_hello_proto_enumTypes[0]
}

func (x GrpcStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrpcStatusCode.Descriptor instead.
func (GrpcStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_hello_hello_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_INVALID  Priority = 0
	Priority_LOW      Priority = 1
	Priority_MEDIUM   Priority = 2
	Priority_HIGH     Priority = 3
	Priority_CRITICAL Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "INVALID",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Priority_value = map[string]int32{
		"INVALID":  0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_hello_hello_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_hello_hello_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_hello_hello_proto_rawDescGZIP(), []int{1}
}

type ErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          GrpcStatusCode         `protobuf:"varint,1,opt,name=code,proto3,enum=hello.GrpcStatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []*anypb.Any           `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorRequest) Reset() {
	*x = ErrorRequest{}
	mi := &file_hello_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRequest) ProtoMessage() {}

func (x *ErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRequest.ProtoReflect.Descriptor instead.
func (*ErrorRequest) Descriptor() ([]byte, []int) {
	return file_hello_hello_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorRequest) GetCode() GrpcStatusCode {
	if x != nil {
		return x.Code
	}
	return GrpcStatusCode_OK
}

func (x *ErrorRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorRequest) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_hello_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_hello_hello_proto_rawDescGZIP(), []int{1}
}

type NestedObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Child         *NestedObject          `protobuf:"bytes,3,opt,name=child,proto3,oneof" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedObject) Reset() {
	*x = NestedObject{}
	mi := &file_hello_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedObject) ProtoMessage() {}

func (x *NestedObject) ProtoReflect() protoreflect.Message {
	mi := &file_hello_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedObject.ProtoReflect.Descriptor instead.
func (*NestedObject) Descriptor() ([]byte, []int) {
	return file_hello_hello_proto_rawDescGZIP(), []int{2}
}

func (x *NestedObject) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NestedObject) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NestedObject) GetChild() *NestedObject {
	if x != nil {
		return x.Child
	}
	return nil
}

type EchoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scalar fields
	DoubleValue   float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	FloatValue    float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	Int32Value    int32   `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value    int64   `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint32Value   uint32  `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint64Value   uint64  `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Sint32Value   int32   `protobuf:"zigzag32,7,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value   int64   `protobuf:"zigzag64,8,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	Fixed32Value  uint32  `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	Fixed64Value  uint64  `protobuf:"fixed64,10,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Sfixed32Value int32   `protobuf:"fixed32,11,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value int64   `protobuf:"fixed64,12,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	BoolValue     bool    `protobuf:"varint,13,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue   string  `protobuf:"bytes,14,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue    []byte  `protobuf:"bytes,15,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	// Repeated scalar fields
	RepeatedDouble   []float64 `protobuf:"fixed64,16,rep,packed,name=repeated_double,json=repeatedDouble,proto3" json:"repeated_double,omitempty"`
	RepeatedFloat    []float32 `protobuf:"fixed32,17,rep,packed,name=repeated_float,json=repeatedFloat,proto3" json:"repeated_float,omitempty"`
	RepeatedInt32    []int32   `protobuf:"varint,18,rep,packed,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	RepeatedInt64    []int64   `protobuf:"varint,19,rep,packed,name=repeated_int64,json=repeatedInt64,proto3" json:"repeated_int64,omitempty"`
	RepeatedUint32   []uint32  `protobuf:"varint,20,rep,packed,name=repeated_uint32,json=repeatedUint32,proto3" json:"repeated_uint32,omitempty"`
	RepeatedUint64   []uint64  `protobuf:"varint,21,rep,packed,name=repeated_uint64,json=repeatedUint64,proto3" json:"repeated_uint64,omitempty"`
	RepeatedSint32   []int32   `protobuf:"zigzag32,22,rep,packed,name=repeated_sint32,json=repeatedSint32,proto3" json:"repeated_sint32,omitempty"`
	RepeatedSint64   []int64   `protobuf:"zigzag64,23,rep,packed,name=repeated_sint64,json=repeatedSint64,proto3" json:"repeated_sint64,omitempty"`
	RepeatedFixed32  []uint32  `protobuf:"fixed32,24,rep,packed,name=repeated_fixed32,json=repeatedFixed32,proto3" json:"repeated_fixed32,omitempty"`
	RepeatedFixed64  []uint64  `protobuf:"fixed64,25,rep,packed,name=repeated_fixed64,json=repeatedFixed64,proto3" json:"repeated_fixed64,omitempty"`
	RepeatedSfixed32 []int32   `protobuf:"fixed32,26,rep,packed,name=repeated_sfixed32,json=repeatedSfixed32,proto3" json:"repeated_sfixed32,omitempty"`
	RepeatedSfixed64 []int64   `protobuf:"fixed64,27,rep,packed,name=repeated_sfixed64,json=repeatedSfixed64,proto3" json:"repeated_sfixed64,omitempty"`
	RepeatedBool     []bool    `protobuf:"varint,28,rep,packed,name=repeated_bool,json=repeatedBool,proto3" json:"repeated_bool,omitempty"`
	RepeatedString   []string  `protobuf:"bytes,29,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	RepeatedBytes    [][]byte  `protobuf:"bytes,30,rep,name=repeated_bytes,json=repeatedBytes,proto3" json:"repeated_bytes,omitempty"`
	// Single object
	NestedObject *NestedObject `protobuf:"bytes,31,opt,name=nested_object,json=nestedObject,proto3" json:"nested_object,omitempty"`
	// Array of objects
	NestedObjectList []*NestedObject `protobuf:"bytes,32,rep,name=nested_object_list,json=nestedObjectList,proto3" json:"nested_object_list,omitempty"`
	// Optional scalar fields (explicit presence)
	OptDouble   *float64 `protobuf:"fixed64,33,opt,name=opt_double,json=optDouble,proto3,oneof" json:"opt_double,omitempty"`
	OptFloat    *float32 `protobuf:"fixed32,34,opt,name=opt_float,json=optFloat,proto3,oneof" json:"opt_float,omitempty"`
	OptInt32    *int32   `protobuf:"varint,35,opt,name=opt_int32,json=optInt32,proto3,oneof" json:"opt_int32,omitempty"`
	OptInt64    *int64   `protobuf:"varint,36,opt,name=opt_int64,json=optInt64,proto3,oneof" json:"opt_int64,omitempty"`
	OptUint32   *uint32  `protobuf:"varint,37,opt,name=opt_uint32,json=optUint32,proto3,oneof" json:"opt_uint32,omitempty"`
	OptUint64   *uint64  `protobuf:"varint,38,opt,name=opt_uint64,json=optUint64,proto3,oneof" json:"opt_uint64,omitempty"`
	OptSint32   *int32   `protobuf:"zigzag32,39,opt,name=opt_sint32,json=optSint32,proto3,oneof" json:"opt_sint32,omitempty"`
	OptSint64   *int64   `protobuf:"zigzag64,40,opt,name=opt_sint64,json=optSint64,proto3,oneof" json:"opt_sint64,omitempty"`
	OptFixed32  *uint32  `protobuf:"fixed32,41,opt,name=opt_fixed32,json=optFixed32,proto3,oneof" json:"opt_fixed32,omitempty"`
	OptFixed64  *uint64  `protobuf:"fixed64,42,opt,name=opt_fixed64,json=optFixed64,proto3,oneof" json:"opt_fixed64,omitempty"`
	OptSfixed32 *int32   `protobuf:"fixed32,43,opt,name=opt_sfixed32,json=optSfixed32,proto3,oneof" json:"opt_sfixed32,omitempty"`
	OptSfixed64 *int64   `protobuf:"fixed64,44,opt,name=opt_sfixed64,json=optSfixed64,proto3,oneof" json:"opt_sfixed64,omitempty"`
	OptBool     *bool    `protobuf:"varint,45,opt,name=opt_bool,json=optBool,proto3,oneof" json:"opt_bool,omitempty"`
	OptString   *string  `protobuf:"bytes,46,opt,name=opt_string,json=optString,proto3,oneof" json:"opt_string,omitempty"`
	OptBytes    []byte   `protobuf:"bytes,47,opt,name=opt_bytes,json=optBytes,proto3,oneof" json:"opt_bytes,omitempty"`
	// Deprecated field for UI testing
	//
	// Deprecated: Marked as deprecated in hello/hello.proto.
	OldField string `protobuf:"bytes,64,opt,name=old_field,json=oldField,proto3" json:"old_field,omitempty"`
	// Enum field
	Priority Priority `protobuf:"varint,65,opt,name=priority,proto3,enum=hello.Priority" json:"priority,omitempty"`
	// Well-known types
	TimestampValue    *timestamppb.Timestamp   `protobuf:"bytes,66,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	DurationValue     *durationpb.Duration     `protobuf:"bytes,67,opt,name=duration_value,json=durationValue,proto3" json:"duration_value,omitempty"`
	FieldMaskValue    *fieldmaskpb.FieldMask   `protobuf:"bytes,68,opt,name=field_mask_value,json=fieldMaskValue,proto3" json:"field_mask_value,omitempty"`
	StringWrapper     *wrapperspb.StringValue  `protobuf:"bytes,69,opt,name=string_wrapper,json=stringWrapper,proto3" json:"string_wrapper,omitempty"`
	BoolWrapper       *wrapperspb.BoolValue    `protobuf:"bytes,70,opt,name=bool_wrapper,json=boolWrapper,proto3" json:"bool_wrapper,omitempty"`
	Int32Wrapper      *wrapperspb.Int32Value   `protobuf:"bytes,71,opt,name=int32_wrapper,json=int32Wrapper,proto3" json:"int32_wrapper,omitempty"`
	Int64Wrapper      *wrapperspb.Int64Value   `protobuf:"bytes,72,opt,name=int64_wrapper,json=int64Wrapper,proto3" json:"int64_wrapper,omitempty"`
	Uint32Wrapper     *wrapperspb.UInt32Value  `protobuf:"bytes,73,opt,name=uint32_wrapper,json=uint32Wrapper,proto3" json:"uint32_wrapper,omitempty"`
	Uint64Wrapper     *wrapperspb.UInt64Value  `protobuf:"bytes,74,opt,name=uint64_wrapper,json=uint64Wrapper,proto3" json:"uint64_wrapper,omitempty"`
	FloatWrapper      *wrapperspb.FloatValue   `protobuf:"bytes,75,opt,name=float_wrapper,json=floatWrapper,proto3" json:"float_wrapper,omitempty"`
	DoubleWrapper     *wrapperspb.DoubleValue  `protobuf:"bytes,76,opt,name=double_wrapper,json=doubleWrapper,proto3" json:"double_wrapper,omitempty"`
	BytesWrapper      *wrapperspb.BytesValue   `protobuf:"bytes,77,opt,name=bytes_wrapper,json=bytesWrapper,proto3" json:"bytes_wrapper,omitempty"`
	AnyValue          *anypb.Any               `protobuf:"bytes,78,opt,name=any_value,json=anyValue,proto3" json:"any_value,omitempty"`
	StructValue       *structpb.Struct         `protobuf:"bytes,79,opt,name=struct_value,json=structValue,proto3" json:"struct_value,omitempty"`
	ListValue         *structpb.ListValue      `protobuf:"bytes,80,opt,name=list_value,json=listValue,proto3" json:"list_value,omitempty"`
	Value             *structpb.Value          `protobuf:"bytes,81,opt,name=value,proto3" json:"value,omitempty"`
	RepeatedTimestamp []*timestamppb.Timestamp `protobuf:"bytes,82,rep,name=repeated_timestamp,json=repeatedTimestamp,proto3" json:"repeated_timestamp,omitempty"`
	RepeatedDuration  []*durationpb.Duration   `protobuf:"bytes,83,rep,name=repeated_duration,json=repeatedDuration,proto3" json:"repeated_duration,omitempty"`
	RepeatedAny       []*anypb.Any             `protobuf:"bytes,84,rep,name=repeated_any,json=repeatedAny,proto3" json:"repeated_any,omitempty"`
	// Test maps
	MapStringString map[string]string        `protobuf:"bytes,85,rep,name=map_string_string,json=mapStringString,proto3" json:"map_string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringObject map[string]*NestedObject `protobuf:"bytes,86,rep,name=map_string_object,json=mapStringObject,proto3" json:"map_string_object,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt32Int32   map[int32]int32          `protobuf:"bytes,87,rep,name=map_int32_int32,json=mapInt32Int32,proto3" json:"map_int32_int32,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Oneof with all scalar types + one object
	//
	// Types that are valid to be assigned to OneofValue:
	//
	//	*EchoRequest_OneofDouble
	//	*EchoRequest_OneofFloat
	//	*EchoRequest_OneofInt32
	//	*EchoRequest_OneofInt64
	//	*EchoRequest_OneofUint32
	//	*EchoRequest_OneofUint64
	//	*EchoRequest_OneofSint32
	//	*EchoRequest_OneofSint64
	//	*EchoRequest_OneofFixed32
	//	*EchoRequest_OneofFixed64
	//	*EchoRequest_OneofSfixed32
	//	*EchoRequest_OneofSfixed64
	//	*EchoRequest_OneofBool
	//	*EchoRequest_OneofString
	//	*EchoRequest_OneofBytes
	//	*EchoRequest_OneofObject
	OneofValue    isEchoRequest_OneofValue `protobuf_oneof:"oneof_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_hello_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_hello_hello_proto_rawDescGZIP(), []int{3}
}

func (x *EchoRequest) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *EchoRequest) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *EchoRequest) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *EchoRequest) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *EchoRequest) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *EchoRequest) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *EchoRequest) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *EchoRequest) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *EchoRequest) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *EchoRequest) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *EchoRequest) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *EchoRequest) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *EchoRequest) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *EchoRequest) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *EchoRequest) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *EchoRequest) GetRepeatedDouble() []float64 {
	if x != nil {
		return x.RepeatedDouble
	}
	return nil
}

func (x *EchoRequest) GetRepeatedFloat() []float32 {
	if x != nil {
		return x.RepeatedFloat
	}
	return nil
}

func (x *EchoRequest) GetRepeatedInt32() []int32 {
	if x != nil {
		return x.RepeatedInt32
	}
	return nil
}

func (x *EchoRequest) GetRepeatedInt64() []int64 {
	if x != nil {
		return x.RepeatedInt64
	}
	return nil
}

func (x *EchoRequest) GetRepeatedUint32() []uint32 {
	if x != nil {
		return x.RepeatedUint32
	}
	return nil
}

func (x *EchoRequest) GetRepeatedUint64() []uint64 {
	if x != nil {
		return x.RepeatedUint64
	}
	return nil
}

func (x *EchoRequest) GetRepeatedSint32() []int32 {
	if x != nil {
		return x.RepeatedSint32
	}
	return nil
}

func (x *EchoRequest) GetRepeatedSint64() []int64 {
	if x != nil {
		return x.RepeatedSint64
	}
	return nil
}

func (x *EchoRequest) GetRepeatedFixed32() []uint32 {
	if x != nil {
		return x.RepeatedFixed32
	}
	return nil
}

func (x *EchoRequest) GetRepeatedFixed64() []uint64 {
	if x != nil {
		return x.RepeatedFixed64
	}
	return nil
}

func (x *EchoRequest) GetRepeatedSfixed32() []int32 {
	if x != nil {
		return x.RepeatedSfixed32
	}
	return nil
}

func (x *EchoRequest) GetRepeatedSfixed64() []int64 {
	if x != nil {
		return x.RepeatedSfixed64
	}
	return nil
}

func (x *EchoRequest) GetRepeatedBool() []bool {
	if x != nil {
		return x.RepeatedBool
	}
	return nil
}

func (x *EchoRequest) GetRepeatedString() []string {
	if x != nil {
		return x.RepeatedString
	}
	return nil
}

func (x *EchoRequest) GetRepeatedBytes() [][]byte {
	if x != nil {
		return x.RepeatedBytes
	}
	return nil
}

func (x *EchoRequest) GetNestedObject() *NestedObject {
	if x != nil {
		return x.NestedObject
	}
	return nil
}

func (x *EchoRequest) GetNestedObjectList() []*NestedObject {
	if x != nil {
		return x.NestedObjectList
	}
	return nil
}

func (x *EchoRequest) GetOptDouble() float64 {
	if x != nil && x.OptDouble != nil {
		return *x.OptDouble
	}
	return 0
}

func (x *EchoRequest) GetOptFloat() float32 {
	if x != nil && x.OptFloat != nil {
		return *x.OptFloat
	}
	return 0
}

func (x *EchoRequest) GetOptInt32() int32 {
	if x != nil && x.OptInt32 != nil {
		return *x.OptInt32
	}
	return 0
}

func (x *EchoRequest) GetOptInt64() int64 {
	if x != nil && x.OptInt64 != nil {
		return *x.OptInt64
	}
	return 0
}

func (x *EchoRequest) GetOptUint32() uint32 {
	if x != nil && x.OptUint32 != nil {
		return *x.OptUint32
	}
	return 0
}

func (x *EchoRequest) GetOptUint64() uint64 {
	if x != nil && x.OptUint64 != nil {
		return *x.OptUint64
	}
	return 0
}

func (x *EchoRequest) GetOptSint32() int32 {
	if x != nil && x.OptSint32 != nil {
		return *x.OptSint32
	}
	return 0
}

func (x *EchoRequest) GetOptSint64() int64 {
	if x != nil && x.OptSint64 != nil {
		return *x.OptSint64
	}
	return 0
}

func (x *EchoRequest) GetOptFixed32() uint32 {
	if x != nil && x.OptFixed32 != nil {
		return *x.OptFixed32
	}
	return 0
}

func (x *EchoRequest) GetOptFixed64() uint64 {
	if x != nil && x.OptFixed64 != nil {
		return *x.OptFixed64
	}
	return 0
}

func (x *EchoRequest) GetOptSfixed32() int32 {
	if x != nil && x.OptSfixed32 != nil {
		return *x.OptSfixed32
	}
	return 0
}

func (x *EchoRequest) GetOptSfixed64() int64 {
	if x != nil && x.OptSfixed64 != nil {
		return *x.OptSfixed64
	}
	return 0
}

func (x *EchoRequest) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

func (x *EchoRequest) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return ""
}

func (x *EchoRequest) GetOptBytes() []byte {
	if x != nil {
		return x.OptBytes
	}
	return nil
}

// Deprecated: Marked as deprecated in hello/hello.proto.
func (x *EchoRequest) GetOldField() string {
	if x != nil {
		return x.OldField
	}
	return ""
}

func (x *EchoRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_INVALID
}

func (x *EchoRequest) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampValue
	}
	return nil
}

func (x *EchoRequest) GetDurationValue() *durationpb.Duration {
	if x != nil {
		return x.DurationValue
	}
	return nil
}

func (x *EchoRequest) GetFieldMaskValue() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMaskValue
	}
	return nil
}

func (x *EchoRequest) GetStringWrapper() *wrapperspb.StringValue {
	if x != nil {
		return x.StringWrapper
	}
	return nil
}

func (x *EchoRequest) GetBoolWrapper() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolWrapper
	}
	return nil
}

func (x *EchoRequest) GetInt32Wrapper() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Wrapper
	}
	return nil
}

func (x *EchoRequest) GetInt64Wrapper() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Wrapper
	}
	return nil
}

func (x *EchoRequest) GetUint32Wrapper() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Wrapper
	}
	return nil
}

func (x *EchoRequest) GetUint64Wrapper() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Wrapper
	}
	return nil
}

func (x *EchoRequest) GetFloatWrapper() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatWrapper
	}
	return nil
}

func (x *EchoRequest) GetDoubleWrapper() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleWrapper
	}
	return nil
}

func (x *EchoRequest) GetBytesWrapper() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesWrapper
	}
	return nil
}

func (x *EchoRequest) GetAnyValue() *anypb.Any {
	if x != nil {
		return x.AnyValue
	}
	return nil
}

func (x *EchoRequest) GetStructValue() *structpb.Struct {
	if x != nil {
		return x.StructValue
	}
	return nil
}

func (x *EchoRequest) GetListValue() *structpb.ListValue {
	if x != nil {
		return x.ListValue
	}
	return nil
}

func (x *EchoRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EchoRequest) GetRepeatedTimestamp() []*timestamppb.Timestamp {
	if x != nil {
		return x.RepeatedTimestamp
	}
	return nil
}

func (x *EchoRequest) GetRepeatedDuration() []*durationpb.Duration {
	if x != nil {
		return x.RepeatedDuration
	}
	return nil
}

func (x *EchoRequest) GetRepeatedAny() []*anypb.Any {
	if x != nil {
		return x.RepeatedAny
	}
	return nil
}

func (x *EchoRequest) GetMapStringString() map[string]string {
	if x != nil {
		return x.MapStringString
	}
	return nil
}

func (x *EchoRequest) GetMapStringObject() map[string]*NestedObject {
	if x != nil {
		return x.MapStringObject
	}
	return nil
}

func (x *EchoRequest) GetMapInt32Int32() map[int32]int32 {
	if x != nil {
		return x.MapInt32Int32
	}
	return nil
}

func (x *EchoRequest) GetOneofValue() isEchoRequest_OneofValue {
	if x != nil {
		return x.OneofValue
	}
	return nil
}

func (x *EchoRequest) GetOneofDouble() float64 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofDouble); ok {
			return x.OneofDouble
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofFloat() float32 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofFloat); ok {
			return x.OneofFloat
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofInt32() int32 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofInt32); ok {
			return x.OneofInt32
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofInt64() int64 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofInt64); ok {
			return x.OneofInt64
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofUint32() uint32 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofUint32); ok {
			return x.OneofUint32
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofUint64() uint64 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofUint64); ok {
			return x.OneofUint64
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofSint32() int32 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofSint32); ok {
			return x.OneofSint32
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofSint64() int64 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofSint64); ok {
			return x.OneofSint64
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofFixed32() uint32 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofFixed32); ok {
			return x.OneofFixed32
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofFixed64() uint64 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofFixed64); ok {
			return x.OneofFixed64
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofSfixed32() int32 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofSfixed32); ok {
			return x.OneofSfixed32
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofSfixed64() int64 {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofSfixed64); ok {
			return x.OneofSfixed64
		}
	}
	return 0
}

func (x *EchoRequest) GetOneofBool() bool {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofBool); ok {
			return x.OneofBool
		}
	}
	return false
}

func (x *EchoRequest) GetOneofString() string {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofString); ok {
			return x.OneofString
		}
	}
	return ""
}

func (x *EchoRequest) GetOneofBytes() []byte {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofBytes); ok {
			return x.OneofBytes
		}
	}
	return nil
}

func (x *EchoRequest) GetOneofObject() *NestedObject {
	if x != nil {
		if x, ok := x.OneofValue.(*EchoRequest_OneofObject); ok {
			return x.OneofObject
		}
	}
	return nil
}

type isEchoRequest_OneofValue interface {
	isEchoRequest_OneofValue()
}

type EchoRequest_OneofDouble struct {
	OneofDouble float64 `protobuf:"fixed64,48,opt,name=oneof_double,json=oneofDouble,proto3,oneof"`
}

type EchoRequest_OneofFloat struct {
	OneofFloat float32 `protobuf:"fixed32,49,opt,name=oneof_float,json=oneofFloat,proto3,oneof"`
}

type EchoRequest_OneofInt32 struct {
	OneofInt32 int32 `protobuf:"varint,50,opt,name=oneof_int32,json=oneofInt32,proto3,oneof"`
}

type EchoRequest_OneofInt64 struct {
	OneofInt64 int64 `protobuf:"varint,51,opt,name=oneof_int64,json=oneofInt64,proto3,oneof"`
}

type EchoRequest_OneofUint32 struct {
	OneofUint32 uint32 `protobuf:"varint,52,opt,name=oneof_uint32,json=oneofUint32,proto3,oneof"`
}

type EchoRequest_OneofUint64 struct {
	OneofUint64 uint64 `protobuf:"varint,53,opt,name=oneof_uint64,json=oneofUint64,proto3,oneof"`
}

type EchoRequest_OneofSint32 struct {
	OneofSint32 int32 `protobuf:"zigzag32,54,opt,name=oneof_sint32,json=oneofSint32,proto3,oneof"`
}

type EchoRequest_OneofSint64 struct {
	OneofSint64 int64 `protobuf:"zigzag64,55,opt,name=oneof_sint64,json=oneofSint64,proto3,oneof"`
}

type EchoRequest_OneofFixed32 struct {
	OneofFixed32 uint32 `protobuf:"fixed32,56,opt,name=oneof_fixed32,json=oneofFixed32,proto3,oneof"`
}

type EchoRequest_OneofFixed64 struct {
	OneofFixed64 uint64 `protobuf:"fixed64,57,opt,name=oneof_fixed64,json=oneofFixed64,proto3,oneof"`
}

type EchoRequest_OneofSfixed32 struct {
	OneofSfixed32 int32 `protobuf:"fixed32,58,opt,name=oneof_sfixed32,json=oneofSfixed32,proto3,oneof"`
}

type EchoRequest_OneofSfixed64 struct {
	OneofSfixed64 int64 `protobuf:"fixed64,59,opt,name=oneof_sfixed64,json=oneofSfixed64,proto3,oneof"`
}

type EchoRequest_OneofBool struct {
	OneofBool bool `protobuf:"varint,60,opt,name=oneof_bool,json=oneofBool,proto3,oneof"`
}

type EchoRequest_OneofString struct {
	OneofString string `protobuf:"bytes,61,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

type EchoRequest_OneofBytes struct {
	OneofBytes []byte `protobuf:"bytes,62,opt,name=oneof_bytes,json=oneofBytes,proto3,oneof"`
}

type EchoRequest_OneofObject struct {
	OneofObject *NestedObject `protobuf:"bytes,63,opt,name=oneof_object,json=oneofObject,proto3,oneof"`
}

func (*EchoRequest_OneofDouble) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofFloat) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofInt32) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofInt64) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofUint32) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofUint64) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofSint32) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofSint64) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofFixed32) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofFixed64) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofSfixed32) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofSfixed64) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofBool) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofString) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofBytes) isEchoRequest_OneofValue() {}

func (*EchoRequest_OneofObject) isEchoRequest_OneofValue() {}

var File_hello_hello_proto protoreflect.FileDescriptor

const file_hello_hello_proto_rawDesc = "" +
	"\n" +
	"\x11hello/hello.proto\x12\x05hello\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x83\x01\n" +
	"\fErrorRequest\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.hello.GrpcStatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\adetails\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\adetails\"\x0f\n" +
	"\rErrorResponse\"t\n" +
	"\fNestedObject\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12.\n" +
	"\x05child\x18\x03 \x01(\v2\x13.hello.NestedObjectH\x00R\x05child\x88\x01\x01B\b\n" +
	"\x06_child\"\xe1\"\n" +
	"\vEchoRequest\x12!\n" +
	"\fdouble_value\x18\x01 \x01(\x01R\vdoubleValue\x12\x1f\n" +
	"\vfloat_value\x18\x02 \x01(\x02R\n" +
	"floatValue\x12\x1f\n" +
	"\vint32_value\x18\x03 \x01(\x05R\n" +
	"int32Value\x12\x1f\n" +
	"\vint64_value\x18\x04 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fuint32_value\x18\x05 \x01(\rR\vuint32Value\x12!\n" +
	"\fuint64_value\x18\x06 \x01(\x04R\vuint64Value\x12!\n" +
	"\fsint32_value\x18\a \x01(\x11R\vsint32Value\x12!\n" +
	"\fsint64_value\x18\b \x01(\x12R\vsint64Value\x12#\n" +
	"\rfixed32_value\x18\t \x01(\aR\ffixed32Value\x12#\n" +
	"\rfixed64_value\x18\n" +
	" \x01(\x06R\ffixed64Value\x12%\n" +
	"\x0esfixed32_value\x18\v \x01(\x0fR\rsfixed32Value\x12%\n" +
	"\x0esfixed64_value\x18\f \x01(\x10R\rsfixed64Value\x12\x1d\n" +
	"\n" +
	"bool_value\x18\r \x01(\bR\tboolValue\x12!\n" +
	"\fstring_value\x18\x0e \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x0f \x01(\fR\n" +
	"bytesValue\x12'\n" +
	"\x0frepeated_double\x18\x10 \x03(\x01R\x0erepeatedDouble\x12%\n" +
	"\x0erepeated_float\x18\x11 \x03(\x02R\rrepeatedFloat\x12%\n" +
	"\x0erepeated_int32\x18\x12 \x03(\x05R\rrepeatedInt32\x12%\n" +
	"\x0erepeated_int64\x18\x13 \x03(\x03R\rrepeatedInt64\x12'\n" +
	"\x0frepeated_uint32\x18\x14 \x03(\rR\x0erepeatedUint32\x12'\n" +
	"\x0frepeated_uint64\x18\x15 \x03(\x04R\x0erepeatedUint64\x12'\n" +
	"\x0frepeated_sint32\x18\x16 \x03(\x11R\x0erepeatedSint32\x12'\n" +
	"\x0frepeated_sint64\x18\x17 \x03(\x12R\x0erepeatedSint64\x12)\n" +
	"\x10repeated_fixed32\x18\x18 \x03(\aR\x0frepeatedFixed32\x12)\n" +
	"\x10repeated_fixed64\x18\x19 \x03(\x06R\x0frepeatedFixed64\x12+\n" +
	"\x11repeated_sfixed32\x18\x1a \x03(\x0fR\x10repeatedSfixed32\x12+\n" +
	"\x11repeated_sfixed64\x18\x1b \x03(\x10R\x10repeatedSfixed64\x12#\n" +
	"\rrepeated_bool\x18\x1c \x03(\bR\frepeatedBool\x12'\n" +
	"\x0frepeated_string\x18\x1d \x03(\tR\x0erepeatedString\x12%\n" +
	"\x0erepeated_bytes\x18\x1e \x03(\fR\rrepeatedBytes\x128\n" +
	"\rnested_object\x18\x1f \x01(\v2\x13.hello.NestedObjectR\fnestedObject\x12A\n" +
	"\x12nested_object_list\x18  \x03(\v2\x13.hello.NestedObjectR\x10nestedObjectList\x12\"\n" +
	"\n" +
	"opt_double\x18! \x01(\x01H\x01R\toptDouble\x88\x01\x01\x12 \n" +
	"\topt_float\x18\" \x01(\x02H\x02R\boptFloat\x88\x01\x01\x12 \n" +
	"\topt_int32\x18# \x01(\x05H\x03R\boptInt32\x88\x01\x01\x12 \n" +
	"\topt_int64\x18$ \x01(\x03H\x04R\boptInt64\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_uint32\x18% \x01(\rH\x05R\toptUint32\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_uint64\x18& \x01(\x04H\x06R\toptUint64\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_sint32\x18' \x01(\x11H\aR\toptSint32\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_sint64\x18( \x01(\x12H\bR\toptSint64\x88\x01\x01\x12$\n" +
	"\vopt_fixed32\x18) \x01(\aH\tR\n" +
	"optFixed32\x88\x01\x01\x12$\n" +
	"\vopt_fixed64\x18* \x01(\x06H\n" +
	"R\n" +
	"optFixed64\x88\x01\x01\x12&\n" +
	"\fopt_sfixed32\x18+ \x01(\x0fH\vR\voptSfixed32\x88\x01\x01\x12&\n" +
	"\fopt_sfixed64\x18, \x01(\x10H\fR\voptSfixed64\x88\x01\x01\x12\x1e\n" +
	"\bopt_bool\x18- \x01(\bH\rR\aoptBool\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_string\x18. \x01(\tH\x0eR\toptString\x88\x01\x01\x12 \n" +
	"\topt_bytes\x18/ \x01(\fH\x0fR\boptBytes\x88\x01\x01\x12\x1f\n" +
	"\told_field\x18@ \x01(\tB\x02\x18\x01R\boldField\x12+\n" +
	"\bpriority\x18A \x01(\x0e2\x0f.hello.PriorityR\bpriority\x12C\n" +
	"\x0ftimestamp_value\x18B \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampValue\x12@\n" +
	"\x0eduration_value\x18C \x01(\v2\x19.google.protobuf.DurationR\rdurationValue\x12D\n" +
	"\x10field_mask_value\x18D \x01(\v2\x1a.google.protobuf.FieldMaskR\x0efieldMaskValue\x12C\n" +
	"\x0estring_wrapper\x18E \x01(\v2\x1c.google.protobuf.StringValueR\rstringWrapper\x12=\n" +
	"\fbool_wrapper\x18F \x01(\v2\x1a.google.protobuf.BoolValueR\vboolWrapper\x12@\n" +
	"\rint32_wrapper\x18G \x01(\v2\x1b.google.protobuf.Int32ValueR\fint32Wrapper\x12@\n" +
	"\rint64_wrapper\x18H \x01(\v2\x1b.google.protobuf.Int64ValueR\fint64Wrapper\x12C\n" +
	"\x0euint32_wrapper\x18I \x01(\v2\x1c.google.protobuf.UInt32ValueR\ruint32Wrapper\x12C\n" +
	"\x0euint64_wrapper\x18J \x01(\v2\x1c.google.protobuf.UInt64ValueR\ruint64Wrapper\x12@\n" +
	"\rfloat_wrapper\x18K \x01(\v2\x1b.google.protobuf.FloatValueR\ffloatWrapper\x12C\n" +
	"\x0edouble_wrapper\x18L \x01(\v2\x1c.google.protobuf.DoubleValueR\rdoubleWrapper\x12@\n" +
	"\rbytes_wrapper\x18M \x01(\v2\x1b.google.protobuf.BytesValueR\fbytesWrapper\x121\n" +
	"\tany_value\x18N \x01(\v2\x14.google.protobuf.AnyR\banyValue\x12:\n" +
	"\fstruct_value\x18O \x01(\v2\x17.google.protobuf.StructR\vstructValue\x129\n" +
	"\n" +
	"list_value\x18P \x01(\v2\x1a.google.protobuf.ListValueR\tlistValue\x12,\n" +
	"\x05value\x18Q \x01(\v2\x16.google.protobuf.ValueR\x05value\x12I\n" +
	"\x12repeated_timestamp\x18R \x03(\v2\x1a.google.protobuf.TimestampR\x11repeatedTimestamp\x12F\n" +
	"\x11repeated_duration\x18S \x03(\v2\x19.google.protobuf.DurationR\x10repeatedDuration\x127\n" +
	"\frepeated_any\x18T \x03(\v2\x14.google.protobuf.AnyR\vrepeatedAny\x12S\n" +
	"\x11map_string_string\x18U \x03(\v2'.hello.EchoRequest.MapStringStringEntryR\x0fmapStringString\x12S\n" +
	"\x11map_string_object\x18V \x03(\v2'.hello.EchoRequest.MapStringObjectEntryR\x0fmapStringObject\x12M\n" +
	"\x0fmap_int32_int32\x18W \x03(\v2%.hello.EchoRequest.MapInt32Int32EntryR\rmapInt32Int32\x12#\n" +
	"\foneof_double\x180 \x01(\x01H\x00R\voneofDouble\x12!\n" +
	"\voneof_float\x181 \x01(\x02H\x00R\n" +
	"oneofFloat\x12!\n" +
	"\voneof_int32\x182 \x01(\x05H\x00R\n" +
	"oneofInt32\x12!\n" +
	"\voneof_int64\x183 \x01(\x03H\x00R\n" +
	"oneofInt64\x12#\n" +
	"\foneof_uint32\x184 \x01(\rH\x00R\voneofUint32\x12#\n" +
	"\foneof_uint64\x185 \x01(\x04H\x00R\voneofUint64\x12#\n" +
	"\foneof_sint32\x186 \x01(\x11H\x00R\voneofSint32\x12#\n" +
	"\foneof_sint64\x187 \x01(\x12H\x00R\voneofSint64\x12%\n" +
	"\roneof_fixed32\x188 \x01(\aH\x00R\foneofFixed32\x12%\n" +
	"\roneof_fixed64\x189 \x01(\x06H\x00R\foneofFixed64\x12'\n" +
	"\x0eoneof_sfixed32\x18: \x01(\x0fH\x00R\roneofSfixed32\x12'\n" +
	"\x0eoneof_sfixed64\x18; \x01(\x10H\x00R\roneofSfixed64\x12\x1f\n" +
	"\n" +
	"oneof_bool\x18< \x01(\bH\x00R\toneofBool\x12#\n" +
	"\foneof_string\x18= \x01(\tH\x00R\voneofString\x12!\n" +
	"\voneof_bytes\x18> \x01(\fH\x00R\n" +
	"oneofBytes\x128\n" +
	"\foneof_object\x18? \x01(\v2\x13.hello.NestedObjectH\x00R\voneofObject\x1aB\n" +
	"\x14MapStringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aW\n" +
	"\x14MapStringObjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.hello.NestedObjectR\x05value:\x028\x01\x1a@\n" +
	"\x12MapInt32Int32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\r\n" +
	"\voneof_valueB\r\n" +
	"\v_opt_doubleB\f\n" +
	"\n" +
	"_opt_floatB\f\n" +
	"\n" +
	"_opt_int32B\f\n" +
	"\n" +
	"_opt_int64B\r\n" +
	"\v_opt_uint32B\r\n" +
	"\v_opt_uint64B\r\n" +
	"\v_opt_sint32B\r\n" +
	"\v_opt_sint64B\x0e\n" +
	"\f_opt_fixed32B\x0e\n" +
	"\f_opt_fixed64B\x0f\n" +
	"\r_opt_sfixed32B\x0f\n" +
	"\r_opt_sfixed64B\v\n" +
	"\t_opt_boolB\r\n" +
	"\v_opt_stringB\f\n" +
	"\n" +
	"_opt_bytes*\xc1\x02\n" +
	"\x0eGrpcStatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tCANCELLED\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x03\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x04\x12\r\n" +
	"\tNOT_FOUND\x10\x05\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x06\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\a\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\b\x12\x17\n" +
	"\x13FAILED_PRECONDITION\x10\t\x12\v\n" +
	"\aABORTED\x10\n" +
	"\x12\x10\n" +
	"\fOUT_OF_RANGE\x10\v\x12\x11\n" +
	"\rUNIMPLEMENTED\x10\f\x12\f\n" +
	"\bINTERNAL\x10\r\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x0e\x12\r\n" +
	"\tDATA_LOSS\x10\x0f\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x10*D\n" +
	"\bPriority\x12\v\n" +
	"\aINVALID\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042y\n" +
	"\vEchoService\x12.\n" +
	"\x04Echo\x12\x12.hello.EchoRequest\x1a\x12.hello.EchoRequest\x12:\n" +
	"\rFailWithError\x12\x13.hello.ErrorRequest\x1a\x14.hello.ErrorResponseB\x1eZ\x1cpulsar-grpc/testserver/hellob\x06proto3"

var (
	file_hello_hello_proto_rawDescOnce sync.Once
	file_hello_hello_proto_rawDescData []byte
)

func file_hello_hello_proto_rawDescGZIP() []byte {
	file_hello_hello_proto_rawDescOnce.Do(func() {
		file_hello_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_hello_proto_rawDesc), len(file_hello_hello_proto_rawDesc)))
	})
	return file_hello_hello_proto_rawDescData
}

var file_hello_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hello_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hello_hello_proto_goTypes = []any{
	(GrpcStatusCode)(0),            // 0: hello.GrpcStatusCode
	(Priority)(0),                  // 1: hello.Priority
	(*ErrorRequest)(nil),           // 2: hello.ErrorRequest
	(*ErrorResponse)(nil),          // 3: hello.ErrorResponse
	(*NestedObject)(nil),           // 4: hello.NestedObject
	(*EchoRequest)(nil),            // 5: hello.EchoRequest
	nil,                            // 6: hello.EchoRequest.MapStringStringEntry
	nil,                            // 7: hello.EchoRequest.MapStringObjectEntry
	nil,                            // 8: hello.EchoRequest.MapInt32Int32Entry
	(*anypb.Any)(nil),              // 9: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 11: google.protobuf.Duration
	(*fieldmaskpb.FieldMask)(nil),  // 12: google.protobuf.FieldMask
	(*wrapperspb.StringValue)(nil), // 13: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 14: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),  // 15: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 16: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 17: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 18: google.protobuf.UInt64Value
	(*wrapperspb.FloatValue)(nil),  // 19: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 20: google.protobuf.DoubleValue
	(*wrapperspb.BytesValue)(nil),  // 21: google.protobuf.BytesValue
	(*structpb.Struct)(nil),        // 22: google.protobuf.Struct
	(*structpb.ListValue)(nil),     // 23: google.protobuf.ListValue
	(*structpb.Value)(nil),         // 24: google.protobuf.Value
}
var file_hello_hello_proto_depIdxs = []int32{
	0,  // 0: hello.ErrorRequest.code:type_name -> hello.GrpcStatusCode
	9,  // 1: hello.ErrorRequest.details:type_name -> google.protobuf.Any
	4,  // 2: hello.NestedObject.child:type_name -> hello.NestedObject
	4,  // 3: hello.EchoRequest.nested_object:type_name -> hello.NestedObject
	4,  // 4: hello.EchoRequest.nested_object_list:type_name -> hello.NestedObject
	1,  // 5: hello.EchoRequest.priority:type_name -> hello.Priority
	10, // 6: hello.EchoRequest.timestamp_value:type_name -> google.protobuf.Timestamp
	11, // 7: hello.EchoRequest.duration_value:type_name -> google.protobuf.Duration
	12, // 8: hello.EchoRequest.field_mask_value:type_name -> google.protobuf.FieldMask
	13, // 9: hello.EchoRequest.string_wrapper:type_name -> google.protobuf.StringValue
	14, // 10: hello.EchoRequest.bool_wrapper:type_name -> google.protobuf.BoolValue
	15, // 11: hello.EchoRequest.int32_wrapper:type_name -> google.protobuf.Int32Value
	16, // 12: hello.EchoRequest.int64_wrapper:type_name -> google.protobuf.Int64Value
	17, // 13: hello.EchoRequest.uint32_wrapper:type_name -> google.protobuf.UInt32Value
	18, // 14: hello.EchoRequest.uint64_wrapper:type_name -> google.protobuf.UInt64Value
	19, // 15: hello.EchoRequest.float_wrapper:type_name -> google.protobuf.FloatValue
	20, // 16: hello.EchoRequest.double_wrapper:type_name -> google.protobuf.DoubleValue
	21, // 17: hello.EchoRequest.bytes_wrapper:type_name -> google.protobuf.BytesValue
	9,  // 18: hello.EchoRequest.any_value:type_name -> google.protobuf.Any
	22, // 19: hello.EchoRequest.struct_value:type_name -> google.protobuf.Struct
	23, // 20: hello.EchoRequest.list_value:type_name -> google.protobuf.ListValue
	24, // 21: hello.EchoRequest.value:type_name -> google.protobuf.Value
	10, // 22: hello.EchoRequest.repeated_timestamp:type_name -> google.protobuf.Timestamp
	11, // 23: hello.EchoRequest.repeated_duration:type_name -> google.protobuf.Duration
	9,  // 24: hello.EchoRequest.repeated_any:type_name -> google.protobuf.Any
	6,  // 25: hello.EchoRequest.map_string_string:type_name -> hello.EchoRequest.MapStringStringEntry
	7,  // 26: hello.EchoRequest.map_string_object:type_name -> hello.EchoRequest.MapStringObjectEntry
	8,  // 27: hello.EchoRequest.map_int32_int32:type_name -> hello.EchoRequest.MapInt32Int32Entry
	4,  // 28: hello.EchoRequest.oneof_object:type_name -> hello.NestedObject
	4,  // 29: hello.EchoRequest.MapStringObjectEntry.value:type_name -> hello.NestedObject
	5,  // 30: hello.EchoService.Echo:input_type -> hello.EchoRequest
	2,  // 31: hello.EchoService.FailWithError:input_type -> hello.ErrorRequest
	5,  // 32: hello.EchoService.Echo:output_type -> hello.EchoRequest
	3,  // 33: hello.EchoService.FailWithError:output_type -> hello.ErrorResponse
	32, // [32:34] is the sub-list for method output_type
	30, // [30:32] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_hello_hello_proto_init() }
func file_hello_hello_proto_init() {
	if File_hello_hello_proto != nil {
		return
	}
	file_hello_hello_proto_msgTypes[2].OneofWrappers = []any{}
	file_hello_hello_proto_msgTypes[3].OneofWrappers = []any{
		(*EchoRequest_OneofDouble)(nil),
		(*EchoRequest_OneofFloat)(nil),
		(*EchoRequest_OneofInt32)(nil),
		(*EchoRequest_OneofInt64)(nil),
		(*EchoRequest_OneofUint32)(nil),
		(*EchoRequest_OneofUint64)(nil),
		(*EchoRequest_OneofSint32)(nil),
		(*EchoRequest_OneofSint64)(nil),
		(*EchoRequest_OneofFixed32)(nil),
		(*EchoRequest_OneofFixed64)(nil),
		(*EchoRequest_OneofSfixed32)(nil),
		(*EchoRequest_OneofSfixed64)(nil),
		(*EchoRequest_OneofBool)(nil),
		(*EchoRequest_OneofString)(nil),
		(*EchoRequest_OneofBytes)(nil),
		(*EchoRequest_OneofObject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_hello_proto_rawDesc), len(file_hello_hello_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_hello_proto_goTypes,
		DependencyIndexes: file_hello_hello_proto_depIdxs,
		EnumInfos:         file_hello_hello_proto_enumTypes,
		MessageInfos:      file_hello_hello_proto_msgTypes,
	}.Build()
	File_hello_hello_proto = out.File
	file_hello_hello_proto_goTypes = nil
	file_hello_hello_proto_depIdxs = nil
}
